export const UI_TEXT = {
  common: {
    home: 'Trang chủ',
    products: 'Sản phẩm',
    clothing: 'Quần áo',
    shoes: 'Giày dép',
    accessories: 'Phụ kiện',
    newArrivals: 'Hàng mới về',
    search: 'Tìm kiếm sản phẩm...',
    cart: 'Giỏ hàng',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    profile: 'Hồ sơ cá nhân',
    admin: 'Quản trị',
    loading: 'Đang tải...',
    error: 'Đã có lỗi xảy ra. Vui lòng thử lại.',
    save: 'Lưu thay đổi',
    cancel: 'Hủy bỏ',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    viewDetails: 'Xem chi tiết',
    addToCart: 'Thêm vào giỏ hàng',
    buyNow: 'Mua ngay',
    checkout: 'Thanh toán',
    back: 'Quay lại',
    next: 'Tiếp theo',
    previous: 'Trước đó',
    all: 'Tất cả',
    filter: 'Bộ lọc',
    sort: 'Sắp xếp',
    noResults: 'Không tìm thấy sản phẩm phù hợp',
  },
  header: {
    searchPlaceholder: 'Tìm kiếm sản phẩm...',
    signedInAs: 'Đăng nhập với tư cách',
    myOrders: 'Đơn hàng của tôi',
    accountSettings: 'Cài đặt tài khoản',
  },
  footer: {
    description: 'NovaKit - Điểm đến hàng đầu cho những tâm hồn yêu thời trang và phong cách sống hiện đại.',
    support: 'Hỗ trợ',
    company: 'Công ty',
    shop: 'Cửa hàng',
    followUs: 'Theo dõi chúng tôi',
    subscribe: 'Đăng ký nhận tin',
    subscribePlaceholder: 'Nhập email của bạn...',
    join: 'THAM GIA',
    rights: 'Bản quyền thuộc về NovaKit Fashion.',
  },
  home: {
    heroBadge: 'NOVAKIT TRENDS 2026',
    heroTitle: 'NOVAKIT <br /> <span class="text-white/40">FASHION</span>',
    heroSub: 'Nâng tầm phong cách cá nhân với bộ sưu tập NovaKit mới nhất. Nơi hội tụ tinh hoa thời trang đương đại.',
    shopNow: 'MUA SẮM NGAY',
    viewFootwear: 'Xem giày dép',
    popularCategories: 'Danh mục phổ biến',
    viewAll: 'Xem tất cả',
    featuredCollection: 'Bộ sưu tập nổi bật',
    featuredSub: 'Lựa chọn tinh tuyển từ các mặt hàng cao cấp định hình phong cách đô thị hiện đại.',
    brandPartners: 'Đối tác thương hiệu',
    ctaTitle: 'NHẬN ƯU ĐÃI 20% CHO ĐƠN HÀNG ĐẦU TIÊN',
    ctaSub: 'Tham gia câu lạc bộ thành viên của chúng tôi để cập nhật những đợt ra mắt mới nhất và ưu đãi độc quyền.',
    registerNow: 'ĐĂNG KÝ NGAY',
  },
  products: {
    title: 'Tất cả sản phẩm',
    breadcrumb: 'Trang chủ / Sản phẩm',
    showing: 'Hiển thị {count} mặt hàng cao cấp',
    sortNewest: 'Mới nhất',
    sortPriceLow: 'Giá: Thấp đến Cao',
    sortPriceHigh: 'Giá: Cao đến Thấp',
    sortPopular: 'Phổ biến nhất',
    filters: 'Bộ lọc',
    clearFilters: 'Xóa tất cả bộ lọc',
    category: 'Danh mục',
    brand: 'Thương hiệu',
    priceRange: 'Khoảng giá (VNĐ)',
    size: 'Kích thước',
    color: 'Màu sắc',
    clothingDesc: 'Khám phá bộ sưu tập thời trang hiện đại, từ áo thun năng động đến những bộ đồ tinh tế cho mọi dịp.',
    shoesDesc: 'Bước đi tự tin với những mẫu giày từ các thương hiệu lừng danh. Sự kết hợp hoàn hảo giữa công nghệ và phong cách.',
    newArrivalsTitle: 'BỘ SƯU TẬP MỚI NHẤT',
    newArrivalsDesc: 'Luôn dẫn đầu xu hướng với những thiết kế vừa ra mắt. Đẳng cấp và thời thượng.',
  },
  cart: {
    title: 'GIỎ HÀNG',
    emptyTitle: 'Giỏ hàng của bạn đang trống',
    emptySub: 'Có vẻ như bạn chưa thêm sản phẩm nào vào giỏ. Hãy khám phá các sản phẩm của chúng tôi ngay!',
    startShopping: 'BẮT ĐẦU MUA SẮM',
    reviewItems: 'Xem sản phẩm',
    clearBag: 'XÓA GIỎ HÀNG',
    summary: 'Tóm tắt đơn hàng',
    subtotal: 'Tạm tính',
    shipping: 'Phí vận chuyển',
    free: 'MIỄN PHÍ',
    tax: 'Thuế (VAT 10%)',
    total: 'Tổng cộng',
    proceed: 'TIẾN HÀNH THANH TOÁN',
    guarantee: 'Giao hàng đảm bảo trong 3-5 ngày',
    paymentMethods: 'Phương thức thanh toán chấp nhận:',
  },
  checkout: {
    title: 'THANH TOÁN',
    shippingInfo: 'Thông tin vận chuyển',
    fullName: 'Họ và tên',
    email: 'Địa chỉ Email',
    phone: 'Số điện thoại',
    city: 'Tỉnh / Thành phố',
    address: 'Địa chỉ cụ thể',
    paymentMethod: 'Phương thức thanh toán',
    cod: 'Thanh toán khi nhận hàng (COD)',
    codSub: 'Thanh toán bằng tiền mặt khi giao hàng',
    card: 'Thẻ tín dụng / Ngân hàng',
    cardSub: 'Hiện chưa hỗ trợ',
    placeOrder: 'ĐẶT HÀNG NGAY',
    reviewOrder: 'Kiểm tra đơn hàng',
    items: 'SẢN PHẨM',
    totalCost: 'Tổng giá trị',
    secureInfo: 'Thông tin cá nhân của bạn được mã hóa và bảo mật tuyệt đối.',
    successTitle: 'Cảm ơn bạn đã đặt hàng!',
    successSub: 'Đơn hàng của bạn đã được tiếp nhận thành công. Chúng tôi sẽ gửi email xác nhận cho bạn sớm nhất.',
    trackOrder: 'THEO DÕI ĐƠN HÀNG',
  },
  auth: {
    loginTitle: 'Chào mừng trở lại',
    loginSub: 'Đăng nhập vào tài khoản của bạn để tiếp tục.',
    registerTitle: 'Tạo tài khoản mới',
    registerSub: 'Điền thông tin của bạn để bắt đầu mua sắm.',
    joinClub: 'Tham gia câu lạc bộ',
    joinClubSub: 'Nhận đặc quyền truy cập các đợt phát hành mới, ưu đãi đặc biệt và đề xuất cá nhân hóa.',
    freeShipping: 'Miễn phí vận chuyển đơn đầu tiên',
    earlyAccess: 'Truy cập sớm các đợt giảm giá',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    alreadyHaveAccount: 'Đã có tài khoản?',
    donHaveAccount: 'Chưa có tài khoản?',
    signIn: 'Đăng nhập',
    signUp: 'Đăng ký',
    processing: 'ĐANG XỬ LÝ...',
  },
  about: {
    heroTitle: 'CÂU CHUYỆN <br /> <span class="text-white/40">THƯƠNG HIỆU</span>',
    heroSub: 'Khởi đầu từ niềm đam mê thời trang thuần khiết, NovaKit không chỉ bán quần áo, chúng tôi kiến tạo phong cách sống.',
    visionTitle: 'Tầm nhìn & Sứ mệnh',
    visionSub: 'Trở thành biểu tượng thời trang đương đại, kết nối cộng đồng qua những thiết kế tối giản và bền vững.',
    coreValues: 'Giá trị cốt lõi',
    historyTitle: 'Hành trình phát triển',
    historySub: 'Từ một studio nhỏ tại Sài Gòn, NovaKit đã vươn mình trở thành điểm đến hàng đầu cho những tâm hồn yêu cái đẹp.',
    whyChooseUs: 'Tại sao chọn NovaKit?',
    statsTitle: 'Con số ấn tượng',
    quality: 'Chất lượng Thượng hạng',
    qualitySub: 'Tuyển chọn chất liệu cao cấp nhất.',
    design: 'Thiết kế Đẳng cấp',
    designSub: 'Luôn đón đầu xu hướng toàn cầu.',
    service: 'Dịch vụ Tận tâm',
    serviceSub: 'Trải nghiệm khách hàng là ưu tiên.',
    viewProducts: 'KHÁM PHÁ SẢN PHẨM',
  },
  contact: {
    title: 'LIÊN HỆ VỚI <br /> <span class="text-black/20">CHÚNG TÔI</span>',
    subtitle: 'Đội ngũ hỗ trợ luôn sẵn sàng giải đáp mọi thắc mắc của bạn 24/7.',
    formTitle: 'Gửi lời nhắn',
    infoTitle: 'Thông tin liên hệ',
    address: 'Địa chỉ trụ sở',
    workingHours: 'Giờ làm việc',
    workingHoursSub: 'Thứ 2 - Chủ Nhật: 09:00 - 21:00',
    sendSuccess: 'LỜI NHẮN ĐÃ ĐƯỢC GỬI THÀNH CÔNG!',
    sendError: 'CÓ LỖI XẢY RA, VUI LÒNG THỬ LẠI.',
    submit: 'GỬI LIÊN HỆ NGAY',
  },
  profile: {
    title: 'Thông tin cá nhân',
    orders: 'Lịch sử đơn hàng',
    settings: 'Cài đặt tài khoản',
    membership: 'Thành viên thân thiết',
    proLevel: 'CẤP ĐỘ CHUYÊN NGHIỆP',
    memberPoints: 'Bạn còn cách 1.200 điểm để lên hạng BẠCH KIM.',
    viewRewards: 'XEM PHẦN THƯỞNG',
    details: 'Chi tiết cá nhân',
    savedPayment: 'Phương thức thanh toán đã lưu',
    addNewCard: 'THÊM THẺ MỚI',
    noOrders: 'Chưa có đơn hàng nào',
    totalPaid: 'Tổng thanh toán',
  },
  admin: {
    dashboard: 'Bảng điều khiển',
    inventory: 'Quản lý kho hàng',
    orders: 'Quản lý đơn hàng',
    analytics: 'Phân tích',
    totalRevenue: 'Tổng doanh thu',
    totalOrders: 'Tổng đơn hàng',
    totalCustomers: 'Tổng khách hàng',
    avgOrder: 'Giá trị đơn hàng TB',
    recentTransactions: 'Giao dịch gần đây',
    inventoryHealth: 'Sức khỏe kho hàng',
    downloadReport: 'TẢI BÁO CÁO',
    newProduct: 'THÊM SẢN PHẨM MỚI',
    productDetails: 'Chi tiết sản phẩm',
    saveProduct: 'LƯU SẢN PHẨM',
  }
};
